# Copyright 2022 Canonical Ltd.
# See LICENSE file for licensing details.
#

options:
  alertmanager_config:
    type: string
    description: |
      Alertmanager configuration in YAML format, with the exclusion of the templates section.
      Refer to https://www.prometheus.io/docs/alerting/latest/configuration/ for full details.
    default: ""
  alertmanager_template:
    type: string
    description: |
      Alertmanager templates definition in YAML format. This is a slight deviation from the official
      alertmanager config spec. All templates need to go into this single config option, instead of
      the 'templates' section of the main configuration file. Refer to
      https://prometheus.io/docs/alerting/latest/notification_examples/ for more details
      on templates.
    default: ""
  s3:
    type: string
    description: |
      Credentials for an S3 object storage system. The credentials must in the form of a string that
      can be deserialized as a YAML object. The top level YAML object is a mapping. The keys in this
      mapping must provide the requisite S3 credentials. This configuration must be identical to the
      s3 configuration provided to Mimir Reader that will be related with this charm.
    default: ""
